# Generated by Django 2.0.2 on 2018-12-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_infomodelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='example1',
            field=models.CharField(blank=True, max_length=150, verbose_name='example'),
        ),
    ]
