# Generated by Django 2.0.2 on 2018-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_example1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='example2',
            field=models.CharField(blank=True, max_length=150, verbose_name='example'),
        ),
        migrations.AddField(
            model_name='user',
            name='example3',
            field=models.CharField(blank=True, max_length=150, verbose_name='example'),
        ),
    ]
