# Generated by Django 2.0.2 on 2018-12-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181216_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='example1',
            field=models.CharField(blank=True, max_length=150, verbose_name='example1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='example2',
            field=models.CharField(blank=True, max_length=150, verbose_name='example2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='example3',
            field=models.CharField(blank=True, max_length=150, verbose_name='example3'),
        ),
    ]
