# Generated by Django 2.0.2 on 2019-01-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181223_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.CharField(blank=True, max_length=150, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.CharField(blank=True, max_length=150, verbose_name='lng'),
        ),
    ]
